### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by kLeZ** [burnison/tasksync#2]
Hi, I would like to know how to configure task sync.
I found config.py, but it's not very well commented inside and it is not documented at all outside in the readme (the only documentation I found on your project).
How do I properly make tasksync work?

**Comment by nekrum** [comment]
Hi,  
to get client_id an client_secret you need to follow:
https://developers.google.com/google-apps/tasks/quickstart/python

**Comment by burnison** [comment]
I have updated the README (only 4 years in the making!)
