### ISSUE TITLE
taskw 404 question

### ISSUE THREAD

**Issue by ghost** [burnison/tasksync#3]
I am getting the following 404 error when installing:

"
Installed /usr/local/lib/python2.7/dist-packages/tasksync-1.0.0-py2.7.egg
Processing dependencies for tasksync==1.0.0
Searching for taskw==0.5.1
Best match: taskw 0.5.1
Downloading https://github.com/burnison/taskw/tarball/completed_task_inclusion#egg=taskw-0.5.1
error: Can't download https://github.com/burnison/taskw/tarball/completed_task_inclusion: 404 Not Found
"

I have taskwarrior installed and also installed taskw via python's pip, but I got the latest version installed (0.8.3). What can I do the get the installation completed?

Thanks.

**Comment by nekrum** [comment]
Hi, 
you  need to remove **taskw** in setup.py, and run:

`python setup.py install.`

Then install taskw by pip.

`pip install taskw`

**Comment by jrmiller82** [comment]
This repo needs way better documentation...

**Comment by burnison** [comment]
I've dusted off this repo and updated the documentation (4 years later?!). Please let me know if that helps.
