### ISSUE TITLE
Need config and install info

### ISSUE THREAD

**Issue by boydkelly** [burnison/tasksync#5]
Hi,
Would be awesome to get this to work.   But installing this is pretty much guesswork.   I found that the pip install taskw command as suggested in another issue will install the latest version 1.2.0 but version 0.5.1 is required for tasksync.  

Download the correct version here:
https://pypi.python.org/pypi/taskw/0.5.1

Configure the client_id and client_secret here:
https://console.developers.google.com/projectselector/apis/credentials

I added the client_id and client_secret to the config.py file before running python setup.py build and pythong setup.py install.

The issue now is if i run tasksync it complains that it can't access the .tasksync/google.oauth' file.  I'm currently trying to find out what the syntax of that is now...  Any suggestions?

**Comment by burnison** [comment]
I have updated the project README. At the current time, I do really just recommend running the project from a `virtualenv`, and I've provided some pretty rough steps.  Unfortunately, making this a bit more user friendly isn't a current priority (PRs welcome!), but if you could provide a bit more information, I may be able to help you get unstuck (for example, I don't have a Windows install to test it on, so I'm also not positive it'll work out of the box)

First, however, I do recommend you check-out master, as I've pushed through a number of changes.
