### ISSUE TITLE
Update the setup.py

### ISSUE THREAD

**Issue by Efendi42** [burnison/tasksync#7]
Please update the setup.py file at line 
23        dependency_links = [
24           'https://github.com/burnison/taskw/tarball/completed_task_inclusion#egg=taskw-0.5.1'],
to:
23        dependency_links = [
24           'https://github.com/burnison/taskw.git'],

Thanx!

**Comment by burnison** [comment]
I've pushed a change that uses the latest `taskw`. This should solve the problem.
